// <auto-generated />
using Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Api.Data.Migrations
{
    [DbContext(typeof(VaccineContext))]
    [Migration("20210921053553_VaccineMigrationBase")]
    partial class VaccineMigrationBase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("Api.Entities.Company", b =>
                {
                    b.Property<string>("CompanyCode")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("CompanyCode");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Api.Entities.Employee", b =>
                {
                    b.Property<string>("EmpCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("AadharNumber")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyCode")
                        .HasColumnType("TEXT");

                    b.Property<ushort>("VaccineStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("EmpCode");

                    b.HasIndex("CompanyCode");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Api.Entities.Employee", b =>
                {
                    b.HasOne("Api.Entities.Company", "company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyCode")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("company");
                });

            modelBuilder.Entity("Api.Entities.Company", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
